export const dateFormat = {
  day: "numeric",
  month: "long",
  year: "numeric",
};
export const dateFormatWithTime = {
  hour: "numeric",
  minute: "numeric",
  day: "numeric",
  month: "long",
  year: "numeric",
};

export const navLinkBgColorLight = "rgba(255, 255, 255, 0.3)";
export const navLinkBgColorDark = "rgba(255, 231, 92, 0.3)";

export const colorSet = [
  { id: 1, light: "#E80909", dark: "#C50707" },
  { id: 2, light: "#FF0090", dark: "#A3005C" },
  { id: 3, light: "#FB5607", dark: "#DD4803" },
  { id: 4, light: "#FFBE0B", dark: "#B88700" },
  { id: 5, light: "#FFEF3D", dark: "#CCBB00" },
  { id: 6, light: "#9AFF57", dark: "#52CC00" },
  { id: 7, light: "#37FF00", dark: "#1B7A00" },
  { id: 8, light: "#39EDBD", dark: "#13CD9C" },
  { id: 9, light: "#00FFE5", dark: "#00A393" },
  { id: 10, light: "#3A86FF", dark: "#1F75FF" },
  { id: 11, light: "#9757EF", dark: "#7F32EC" },
  { id: 12, light: "#CC39ED", dark: "#AB13CD" },
];

export const currencies = {
  EUR: { name: "Euro", symbol: "€" },
  GBP: { name: "British Pound Sterling", symbol: "£" },
  CAD: { name: "Canadian Dollar", symbol: "$" },
  CHF: { name: "Swiss Franc", symbol: "CHf" },
  USD: { name: "US Dollar", symbol: "$" },
  AFA: { name: "Afghan Afghani", symbol: "؋" },
  ALL: { name: "Albanian Lek", symbol: "Lek" },
  DZD: { name: "Algerian Dinar", symbol: "دج" },
  AOA: { name: "Angolan Kwanza", symbol: "Kz" },
  ARS: { name: "Argentine Peso", symbol: "$" },
  AMD: { name: "Armenian Dram", symbol: "֏" },
  AWG: { name: "Aruban Florin", symbol: "ƒ" },
  AUD: { name: "Australian Dollar", symbol: "$" },
  AZN: { name: "Azerbaijani Manat", symbol: "m" },
  BSD: { name: "Bahamian Dollar", symbol: "B$" },
  BHD: { name: "Bahraini Dinar", symbol: ".د.ب" },
  BDT: { name: "Bangladeshi Taka", symbol: "৳" },
  BBD: { name: "Barbadian Dollar", symbol: "Bds$" },
  BYR: { name: "Belarusian Ruble", symbol: "Br" },
  BEF: { name: "Belgian Franc", symbol: "fr" },
  BZD: { name: "Belize Dollar", symbol: "$" },
  BMD: { name: "Bermudan Dollar", symbol: "$" },
  BTN: { name: "Bhutanese Ngultrum", symbol: "Nu." },
  BTC: { name: "Bitcoin", symbol: "฿" },
  BOB: { name: "Bolivian Boliviano", symbol: "Bs." },
  BAM: { name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  BWP: { name: "Botswanan Pula", symbol: "P" },
  BRL: { name: "Brazilian Real", symbol: "R$" },
  BND: { name: "Brunei Dollar", symbol: "B$" },
  BGN: { name: "Bulgarian Lev", symbol: "Лв." },
  BIF: { name: "Burundian Franc", symbol: "FBu" },
  KHR: { name: "Cambodian Riel", symbol: "KHR" },
  CVE: { name: "Cape Verdean Escudo", symbol: "$" },
  KYD: { name: "Cayman Islands Dollar", symbol: "$" },
  XOF: { name: "CFA Franc BCEAO", symbol: "CFA" },
  XAF: { name: "CFA Franc BEAC", symbol: "FCFA" },
  XPF: { name: "CFP Franc", symbol: "₣" },
  CLP: { name: "Chilean Peso", symbol: "$" },
  CNY: { name: "Chinese Yuan", symbol: "¥" },
  COP: { name: "Colombian Peso", symbol: "$" },
  KMF: { name: "Comorian Franc", symbol: "CF" },
  CDF: { name: "Congolese Franc", symbol: "FC" },
  CRC: { name: "Costa Rican ColÃ³n", symbol: "₡" },
  HRK: { name: "Croatian Kuna", symbol: "kn" },
  CUC: { name: "Cuban Convertible Peso", symbol: "$, CUC" },
  CZK: { name: "Czech Republic Koruna", symbol: "Kč" },
  DKK: { name: "Danish Krone", symbol: "Kr." },
  DJF: { name: "Djiboutian Franc", symbol: "Fdj" },
  DOP: { name: "Dominican Peso", symbol: "$" },
  XCD: { name: "East Caribbean Dollar", symbol: "$" },
  EGP: { name: "Egyptian Pound", symbol: "ج.م" },
  ERN: { name: "Eritrean Nakfa", symbol: "Nfk" },
  EEK: { name: "Estonian Kroon", symbol: "kr" },
  ETB: { name: "Ethiopian Birr", symbol: "Nkf" },
  FKP: { name: "Falkland Islands Pound", symbol: "£" },
  FJD: { name: "Fijian Dollar", symbol: "FJ$" },
  GMD: { name: "Gambian Dalasi", symbol: "D" },
  GEL: { name: "Georgian Lari", symbol: "ლ" },
  DEM: { name: "German Mark", symbol: "DM" },
  GHS: { name: "Ghanaian Cedi", symbol: "GH₵" },
  GIP: { name: "Gibraltar Pound", symbol: "£" },
  GRD: { name: "Greek Drachma", symbol: "₯, Δρχ, Δρ" },
  GTQ: { name: "Guatemalan Quetzal", symbol: "Q" },
  GNF: { name: "Guinean Franc", symbol: "FG" },
  GYD: { name: "Guyanaese Dollar", symbol: "$" },
  HTG: { name: "Haitian Gourde", symbol: "G" },
  HNL: { name: "Honduran Lempira", symbol: "L" },
  HKD: { name: "Hong Kong Dollar", symbol: "$" },
  HUF: { name: "Hungarian Forint", symbol: "Ft" },
  ISK: { name: "Icelandic KrÃ³na", symbol: "kr" },
  INR: { name: "Indian Rupee", symbol: "₹" },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp" },
  IRR: { name: "Iranian Rial", symbol: "﷼" },
  IQD: { name: "Iraqi Dinar", symbol: "د.ع" },
  ILS: { name: "Israeli New Sheqel", symbol: "₪" },
  ITL: { name: "Italian Lira", symbol: "L,£" },
  JMD: { name: "Jamaican Dollar", symbol: "J$" },
  JPY: { name: "Japanese Yen", symbol: "¥" },
  JOD: { name: "Jordanian Dinar", symbol: "ا.د" },
  KZT: { name: "Kazakhstani Tenge", symbol: "лв" },
  KES: { name: "Kenyan Shilling", symbol: "KSh" },
  KWD: { name: "Kuwaiti Dinar", symbol: "ك.د" },
  KGS: { name: "Kyrgystani Som", symbol: "лв" },
  LAK: { name: "Laotian Kip", symbol: "₭" },
  LVL: { name: "Latvian Lats", symbol: "Ls" },
  LBP: { name: "Lebanese Pound", symbol: "£" },
  LSL: { name: "Lesotho Loti", symbol: "L" },
  LRD: { name: "Liberian Dollar", symbol: "$" },
  LYD: { name: "Libyan Dinar", symbol: "د.ل" },
  LTL: { name: "Lithuanian Litas", symbol: "Lt" },
  MOP: { name: "Macanese Pataca", symbol: "$" },
  MKD: { name: "Macedonian Denar", symbol: "ден" },
  MGA: { name: "Malagasy Ariary", symbol: "Ar" },
  MWK: { name: "Malawian Kwacha", symbol: "MK" },
  MYR: { name: "Malaysian Ringgit", symbol: "RM" },
  MVR: { name: "Maldivian Rufiyaa", symbol: "Rf" },
  MRO: { name: "Mauritanian Ouguiya", symbol: "MRU" },
  MUR: { name: "Mauritian Rupee", symbol: "₨" },
  MXN: { name: "Mexican Peso", symbol: "$" },
  MDL: { name: "Moldovan Leu", symbol: "L" },
  MNT: { name: "Mongolian Tugrik", symbol: "₮" },
  MAD: { name: "Moroccan Dirham", symbol: "MAD" },
  MZM: { name: "Mozambican Metical", symbol: "MT" },
  MMK: { name: "Myanmar Kyat", symbol: "K" },
  NAD: { name: "Namibian Dollar", symbol: "$" },
  NPR: { name: "Nepalese Rupee", symbol: "₨" },
  ANG: { name: "Netherlands Antillean Guilder", symbol: "ƒ" },
  TWD: { name: "New Taiwan Dollar", symbol: "$" },
  NZD: { name: "New Zealand Dollar", symbol: "$" },
  NIO: { name: "Nicaraguan CÃ³rdoba", symbol: "C$" },
  NGN: { name: "Nigerian Naira", symbol: "₦" },
  KPW: { name: "North Korean Won", symbol: "₩" },
  NOK: { name: "Norwegian Krone", symbol: "kr" },
  OMR: { name: "Omani Rial", symbol: ".ع.ر" },
  PKR: { name: "Pakistani Rupee", symbol: "₨" },
  PAB: { name: "Panamanian Balboa", symbol: "B/." },
  PGK: { name: "Papua New Guinean Kina", symbol: "K" },
  PYG: { name: "Paraguayan Guarani", symbol: "₲" },
  PEN: { name: "Peruvian Nuevo Sol", symbol: "S/." },
  PHP: { name: "Philippine Peso", symbol: "₱" },
  PLN: { name: "Polish Zloty", symbol: "zł" },
  QAR: { name: "Qatari Rial", symbol: "ق.ر" },
  RON: { name: "Romanian Leu", symbol: "lei" },
  RUB: { name: "Russian Ruble", symbol: "₽" },
  RWF: { name: "Rwandan Franc", symbol: "FRw" },
  SVC: { name: "Salvadoran ColÃ³n", symbol: "₡" },
  WST: { name: "Samoan Tala", symbol: "SAT" },
  SAR: { name: "Saudi Riyal", symbol: "﷼" },
  RSD: { name: "Serbian Dinar", symbol: "din" },
  SCR: { name: "Seychellois Rupee", symbol: "SRe" },
  SLL: { name: "Sierra Leonean Leone", symbol: "Le" },
  SGD: { name: "Singapore Dollar", symbol: "$" },
  SKK: { name: "Slovak Koruna", symbol: "Sk" },
  SBD: { name: "Solomon Islands Dollar", symbol: "Si$" },
  SOS: { name: "Somali Shilling", symbol: "Sh.so." },
  ZAR: { name: "South African Rand", symbol: "R" },
  KRW: { name: "South Korean Won", symbol: "₩" },
  XDR: { name: "Special Drawing Rights", symbol: "SDR" },
  LKR: { name: "Sri Lankan Rupee", symbol: "Rs" },
  SHP: { name: "St. Helena Pound", symbol: "£" },
  SDG: { name: "Sudanese Pound", symbol: ".س.ج" },
  SRD: { name: "Surinamese Dollar", symbol: "$" },
  SZL: { name: "Swazi Lilangeni", symbol: "E" },
  SEK: { name: "Swedish Krona", symbol: "kr" },
  SYP: { name: "Syrian Pound", symbol: "LS" },
  STD: { name: "São Tomé and Príncipe Dobra", symbol: "Db" },
  TJS: { name: "Tajikistani Somoni", symbol: "SM" },
  TZS: { name: "Tanzanian Shilling", symbol: "TSh" },
  THB: { name: "Thai Baht", symbol: "฿" },
  TOP: { name: "Tongan Pa'anga", symbol: "$" },
  TTD: { name: "Trinidad & Tobago Dollar", symbol: "$" },
  TND: { name: "Tunisian Dinar", symbol: "ت.د" },
  TRY: { name: "Turkish Lira", symbol: "₺" },
  TMT: { name: "Turkmenistani Manat", symbol: "T" },
  UGX: { name: "Ugandan Shilling", symbol: "USh" },
  UAH: { name: "Ukrainian Hryvnia", symbol: "₴" },
  AED: { name: "United Arab Emirates Dirham", symbol: "إ.د" },
  UYU: { name: "Uruguayan Peso", symbol: "$" },
  UZS: { name: "Uzbekistan Som", symbol: "лв" },
  VUV: { name: "Vanuatu Vatu", symbol: "VT" },
  VEF: { name: "Venezuelan BolÃvar", symbol: "Bs" },
  VND: { name: "Vietnamese Dong", symbol: "₫" },
  YER: { name: "Yemeni Rial", symbol: "﷼" },
  ZMK: { name: "Zambian Kwacha", symbol: "ZK" },
};

export const demoUserData = {
  settings: {
    currency: { name: "Euro", symbol: "€" },
    tags: [
      {
        color: 1,
        name: "Myself",
      },
      {
        name: "Girlfriend",
        color: 2,
      },
      {
        name: "Going out",
        color: 11,
      },
      {
        color: 5,
        name: "Impulse",
      },
      {
        name: "Work-related",
        color: 10,
      },
      {
        name: "Business",
        color: 9,
      },
      {
        name: "Family",
        color: 7,
      },
      {
        color: 4,
        name: "Travels",
      },
    ],
    groups: [
      {
        icon: "🍗",
        name: "Food",
      },
      {
        icon: "🚕",
        name: "Transportation",
      },
      {
        icon: "🎁",
        name: "Gifts",
      },
      {
        name: "Bad Habits",
        icon: "🚬",
      },
      {
        icon: "🔧",
        name: "Services",
      },
      {
        icon: "👨‍⚕️",
        name: "Healthcare",
      },
      {
        name: "Leisure",
        icon: "🕶️",
      },
      {
        name: "Investments",
        icon: "🔝",
      },
      {
        icon: "🛍️",
        name: "Purchases",
      },
    ],
    items: [
      {
        name: "Restaurant",
        parent: "Food",
      },
      {
        parent: "Food",
        name: "Home-Cooked",
      },
      {
        name: "Snacks",
        parent: "Food",
      },
      {
        parent: "Food",
        name: "Delivery",
      },
      {
        parent: "Transportation",
        name: "Gas",
      },
      {
        name: "Taxi",
        parent: "Transportation",
      },
      {
        name: "Personal",
        parent: "Gifts",
      },
      {
        parent: "Gifts",
        name: "Birthdays",
      },
      {
        name: "Fast Food",
        parent: "Bad Habits",
      },
      {
        parent: "Bad Habits",
        name: "Alcohol",
      },
      {
        parent: "Bad Habits",
        name: "Tobacco",
      },
      {
        parent: "Services",
        name: "Utilities",
      },
      {
        name: "Coaching",
        parent: "Services",
      },
      {
        name: "Pharmaceutical",
        parent: "Healthcare",
      },
      {
        name: "Appointments",
        parent: "Healthcare",
      },
      {
        parent: "Leisure",
        name: "Tours",
      },
      {
        parent: "Leisure",
        name: "Culture",
      },
      {
        parent: "Investments",
        name: "Paid Ads",
      },
      {
        name: "Entertainment",
        parent: "Leisure",
      },
      {
        name: "Donations",
        parent: "Gifts",
      },
      {
        name: "Haircut",
        parent: "Services",
      },
      {
        parent: "Purchases",
        name: "Gadgets",
      },
      {
        name: "Appliances",
        parent: "Purchases",
      },
      {
        parent: "Services",
        name: "Network",
      },
      {
        name: "Clothing",
        parent: "Purchases",
      },
    ],
    sources: [
      {
        icon: "💰",
        name: "Salary",
      },
      {
        name: "Tips",
        icon: "💵",
      },
      {
        icon: "🤷‍♂️",
        name: "Odd Jobs",
      },
      {
        icon: "🎩",
        name: "Business",
      },
    ],
    statistics: [
      {
        displayItems: [],
        dateRange: [
          {
            seconds: 1659301200,
            nanoseconds: 0,
          },
          {
            seconds: 1661979599,
            nanoseconds: 59000000,
          },
        ],
        displayTags: [],
        chartType: "Pie",
        displayGroups: [],
        id: 1,
        name: "Income",
        order: 0,
        displaySources: ["Salary", "Tips", "Odd Jobs", "Business"],
      },
      {
        displayItems: ["Fast Food", "Alcohol", "Tobacco"],
        id: 3,
        displaySources: [],
        name: "Bad Habits",
        displayTags: [],
        order: 1,
        dateRange: [
          {
            seconds: 1659301200,
            nanoseconds: 0,
          },
          {
            seconds: 1661979599,
            nanoseconds: 59000000,
          },
        ],
        displayGroups: ["Bad Habits"],
        chartType: "Line",
      },
      {
        displayTags: [],
        displayGroups: ["Food"],
        chartType: "Line",
        order: 2,
        name: "Food choices",
        displaySources: [],
        displayItems: [
          "Restaurant",
          "Home-Cooked",
          "Snacks",
          "Delivery",
          "Fast Food",
        ],
        id: 2,
        dateRange: [
          {
            seconds: 1659301200,
            nanoseconds: 0,
          },
          {
            seconds: 1661979599,
            nanoseconds: 59000000,
          },
        ],
      },
    ],
  },
  entries: [
    {
      sum: 0,
      date: 1661942458000,
    },
    {
      id: "tZE6UWq9aXEsm5FEYWLH",
      isSpending: true,
      date: 1661942458000,
      sum: 75,
      icon: "🍗",
      tags: ["Myself", "Work-related"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      id: "PaTLx3horz9ghuH5xpYK",
      isSpending: true,
      date: 1661942437000,
      sum: 50,
      icon: "🚬",
      tags: ["Work-related", "Myself"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "",
      comment: "",
    },
    {
      id: "Sklw0sVUZCIDvqitn6I1",
      isSpending: true,
      date: 1661942417000,
      sum: 69,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      id: "EaqjjeBeF6UV7lJwwCss",
      isSpending: true,
      date: 1661942395000,
      sum: 435,
      icon: "🛍️",
      tags: ["Myself"],
      group: "Purchases",
      item: "Gadgets",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1661806800000,
    },
    {
      id: "eF2cVxEJczaq42P5jNl1",
      isSpending: true,
      date: 1661806800000,
      sum: 23,
      icon: "🚕",
      tags: ["Girlfriend", "Going out"],
      group: "Transportation",
      item: "Taxi",
      source: "",
      comment: "",
    },
    {
      id: "TqeEEr0Pc0H36g8eMmAS",
      isSpending: true,
      date: 1661806800000,
      sum: 12,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Personal",
      source: "",
      comment: "",
    },
    {
      id: "BHXB8XEra9eBQraRhGh4",
      isSpending: true,
      date: 1661806800000,
      sum: 43,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Delivery",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1661720400000,
    },
    {
      id: "cFJtI8rwiMZPzLD9F89L",
      isSpending: true,
      date: 1661720400000,
      sum: 45,
      icon: "🍗",
      tags: ["Work-related"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1661634000000,
    },
    {
      id: "5g8IUklDBdZYhCZKTVt9",
      isSpending: true,
      date: 1661634000000,
      sum: 47,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Personal",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1661461200000,
    },
    {
      id: "nVvE1NAGYzHtHG3nqiCY",
      isSpending: true,
      date: 1661461200000,
      sum: 153,
      icon: "🍗",
      tags: ["Myself", "Girlfriend", "Going out"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      id: "l33wfsadyg3meUISHOfB",
      isSpending: true,
      date: 1661461200000,
      sum: 25,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Tobacco",
      source: "",
      comment: "",
    },
    {
      id: "Ep3jWOHvsOujsmNxMybv",
      isSpending: true,
      date: 1661461200000,
      sum: 236,
      icon: "🛍️",
      tags: ["Myself"],
      group: "Purchases",
      item: "Clothing",
      source: "",
      comment: "",
    },
    {
      id: "BdVkRUnRiDzd3cAcrsMI",
      isSpending: true,
      date: 1661461200000,
      sum: 15,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Snacks",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1661374800000,
    },
    {
      id: "UnibkYZH3xDeHQrrHwG8",
      isSpending: true,
      date: 1661374800000,
      sum: 47,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Delivery",
      source: "",
      comment: "",
    },
    {
      id: "MwARC4CYREEAA00UShub",
      isSpending: true,
      date: 1661374800000,
      sum: 54,
      icon: "🍗",
      tags: ["Work-related"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      id: "FdvNaurwzLKFQRsDvCfG",
      isSpending: true,
      date: 1661374800000,
      sum: 28,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1661288400000,
    },
    {
      id: "zL0jW3sfK0HIjXErvh3B",
      isSpending: true,
      date: 1661288400000,
      sum: 24,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "",
      comment: "",
    },
    {
      id: "Xn1TeaDSDY9YZQSLLluk",
      isSpending: true,
      date: 1661288400000,
      sum: 32,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Fast Food",
      source: "",
      comment: "",
    },
    {
      id: "OrA7gG3nlY4buB3Pov9p",
      isSpending: true,
      date: 1661288400000,
      sum: 126,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1661115600000,
    },
    {
      id: "J1be8INv7cqkt9c8gxKb",
      isSpending: true,
      date: 1661115600000,
      sum: 324,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "",
      comment: "",
    },
    {
      id: "5zEzjcJyPMJvcenpVmMG",
      isSpending: true,
      date: 1661115600000,
      sum: 48,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Personal",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1660942800000,
    },
    {
      id: "iHgarV8ByEiGX2E7YaQI",
      isSpending: true,
      date: 1660942800000,
      sum: 264,
      icon: "🔧",
      tags: ["Myself"],
      group: "Services",
      item: "Utilities",
      source: "",
      comment: "",
    },
    {
      id: "WbHyoI0KMIA0SlfSmtVd",
      isSpending: true,
      date: 1660942800000,
      sum: 67,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      id: "WUjs4ScYTqt023we6ID8",
      isSpending: true,
      date: 1660942800000,
      sum: 92,
      icon: "🚕",
      tags: ["Myself"],
      group: "Transportation",
      item: "Gas",
      source: "",
      comment: "",
    },
    {
      id: "GYBcTQQRRn5QiySi6rOd",
      isSpending: true,
      date: 1660942800000,
      sum: 52,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1660856400000,
    },
    {
      id: "ibPJpFhOOdriOYkRz5fP",
      isSpending: true,
      date: 1660856400000,
      sum: 713,
      icon: "🎁",
      tags: ["Family"],
      group: "Gifts",
      item: "Birthdays",
      source: "",
      comment: "Dad",
    },
    {
      id: "flH5JKY10KuSO8Y8RJJZ",
      isSpending: true,
      date: 1660856400000,
      sum: 27,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Snacks",
      source: "",
      comment: "",
    },
    {
      id: "aWVdJSaXU4YXRTuOy2Nn",
      isSpending: true,
      date: 1660856400000,
      sum: 46,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Personal",
      source: "",
      comment: "",
    },
    {
      id: "GWhsPjbREIIfVbyopH0K",
      isSpending: true,
      date: 1660856400000,
      sum: 68,
      icon: "👨‍⚕️",
      tags: ["Myself"],
      group: "Healthcare",
      item: "Pharmaceutical",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1660770000000,
    },
    {
      id: "Bh4MK98S9RIcqTd89gYZ",
      isSpending: true,
      date: 1660770000000,
      sum: 39,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Snacks",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1660683600000,
    },
    {
      id: "dWsQjKTfOduUbxtLGSIw",
      isSpending: true,
      date: 1660683600000,
      sum: 93,
      icon: "🚕",
      tags: ["Myself"],
      group: "Transportation",
      item: "Gas",
      source: "",
      comment: "",
    },
    {
      id: "R0OLPZUloajtThtMDHqi",
      isSpending: true,
      date: 1660683600000,
      sum: 200,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Personal",
      source: "",
      comment: "",
    },
    {
      id: "HqsiNXHgfyIyKZi9E5kf",
      isSpending: true,
      date: 1660683600000,
      sum: 36,
      icon: "🚕",
      tags: ["Girlfriend"],
      group: "Transportation",
      item: "Taxi",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1660510800000,
    },
    {
      id: "Ex05vwuqLbuKuSwRwHo1",
      isSpending: true,
      date: 1660510800000,
      sum: 64,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Home-Cooked",
      source: "",
      comment: "",
    },
    {
      id: "9vaBUhTD6Q6zuEuQy7dG",
      isSpending: false,
      date: 1660510800000,
      sum: 6568,
      icon: "🎩",
      tags: [],
      group: "",
      item: "",
      source: "Business",
      comment: "",
    },
    {
      id: "4qL5hyF3Xl3ZUvectfYw",
      isSpending: true,
      date: 1660510800000,
      sum: 5833,
      icon: "🛍️",
      tags: ["Myself"],
      group: "Purchases",
      item: "Gadgets",
      source: "",
      comment: "New PC",
    },
    {
      id: "19HUOZiGkdLdU8aB9zcP",
      isSpending: true,
      date: 1660510800000,
      sum: 16,
      icon: "🔧",
      tags: ["Myself"],
      group: "Services",
      item: "Coaching",
      source: "",
      comment: "Udemy",
    },
    {
      sum: 0,
      date: 1660424400000,
    },
    {
      id: "Rc6MJLsDphQk490L0FPo",
      isSpending: true,
      date: 1660424400000,
      sum: 325,
      icon: "🚕",
      tags: ["Myself"],
      group: "Transportation",
      item: "Gas",
      source: "",
      comment: "",
    },
    {
      id: "NpsuBit3ylzmYts5V2my",
      isSpending: true,
      date: 1660424400000,
      sum: 97,
      icon: "🔧",
      tags: ["Work-related"],
      group: "Services",
      item: "Network",
      source: "",
      comment: "",
    },
    {
      id: "Dlvb0tIGLxiNzGBkYE4w",
      isSpending: true,
      date: 1660424400000,
      sum: 24,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1660338000000,
    },
    {
      id: "VNYb1IQtMlsrB9sukDO8",
      isSpending: true,
      date: 1660338000000,
      sum: 106,
      icon: "🍗",
      tags: ["Myself", "Girlfriend", "Going out"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      id: "QjAfJRAbHXNFXQjTAYWO",
      isSpending: true,
      date: 1660338000000,
      sum: 670,
      icon: "👨‍⚕️",
      tags: ["Myself"],
      group: "Healthcare",
      item: "Appointments",
      source: "",
      comment: "",
    },
    {
      id: "P6Sm26oL4vKKN2ykpfKC",
      isSpending: true,
      date: 1660338000000,
      sum: 82,
      icon: "🍗",
      tags: ["Myself", "Girlfriend", "Going out"],
      group: "Food",
      item: "Snacks",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1660251600000,
    },
    {
      id: "lghgY9FbtZlmHnxprtrR",
      isSpending: true,
      date: 1660251600000,
      sum: 75,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      id: "kQPxZaIRr6QAwJgtsnJZ",
      isSpending: true,
      date: 1660251600000,
      sum: 20,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Personal",
      source: "",
      comment: "",
    },
    {
      id: "STm9jftSUgFgxM7lFOUw",
      isSpending: true,
      date: 1660251600000,
      sum: 194,
      icon: "🚬",
      tags: ["Myself", "Going out"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "",
      comment: "",
    },
    {
      id: "ETDd9frwDKg5eR4O12no",
      isSpending: true,
      date: 1660251600000,
      sum: 54,
      icon: "🚬",
      tags: ["Myself", "Impulse"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "",
      comment: "",
    },
    {
      id: "ESE5ifAIYCdzFQX9Br4M",
      isSpending: true,
      date: 1660251600000,
      sum: 16,
      icon: "🍗",
      tags: ["Myself", "Going out"],
      group: "Food",
      item: "Snacks",
      source: "",
      comment: "",
    },
    {
      id: "BVUirUf7MBgSskUwUhVo",
      isSpending: true,
      date: 1660251600000,
      sum: 20,
      icon: "🚬",
      tags: ["Myself", "Impulse"],
      group: "Bad Habits",
      item: "Tobacco",
      source: "",
      comment: "",
    },
    {
      id: "9ow0bd7xzfEo80hEYpEk",
      isSpending: true,
      date: 1660251600000,
      sum: 25,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1660165200000,
    },
    {
      id: "mK6vopYH9EAxyGc4qzQE",
      isSpending: true,
      date: 1660165200000,
      sum: 85,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "",
      comment: "",
    },
    {
      id: "6JPD3ISsTbAkBVTxAeYj",
      isSpending: true,
      date: 1660165200000,
      sum: 26,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Snacks",
      source: "",
      comment: "",
    },
    {
      id: "3ZseDpbESzLn9Zgz2pp3",
      isSpending: true,
      date: 1660165200000,
      sum: 73,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Personal",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1660078800000,
    },
    {
      id: "LspOEuOcdEtlClHtx8YC",
      isSpending: true,
      date: 1660078800000,
      sum: 50,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "",
      comment: "",
    },
    {
      id: "FRRWYGgKwt0NLNvlqgCD",
      isSpending: true,
      date: 1660078800000,
      sum: 31,
      icon: "👨‍⚕️",
      tags: ["Myself"],
      group: "Healthcare",
      item: "Pharmaceutical",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1659992400000,
    },
    {
      id: "mQJvfcPDEBHZbyXHCnBM",
      isSpending: true,
      date: 1659992400000,
      sum: 56,
      icon: "🍗",
      tags: ["Myself", "Going out"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      id: "fsfJ1Q397C89pO5iDRw2",
      isSpending: true,
      date: 1659992400000,
      sum: 100,
      icon: "🍗",
      tags: ["Myself", "Girlfriend", "Going out"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      id: "Baa0JkYWBGsXgk2GMAxI",
      isSpending: true,
      date: 1659992400000,
      sum: 3,
      icon: "🎁",
      tags: ["Myself"],
      group: "Gifts",
      item: "Donations",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1659906000000,
    },
    {
      id: "RhQn8Uo0RWFdycTDGVP2",
      isSpending: true,
      date: 1659906000000,
      sum: 65,
      icon: "🚕",
      tags: ["Myself", "Girlfriend"],
      group: "Transportation",
      item: "Taxi",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1659819600000,
    },
    {
      id: "flw4W6Y5Lf9T5ni8NZJD",
      isSpending: true,
      date: 1659819600000,
      sum: 12,
      icon: "🕶️",
      tags: ["Myself"],
      group: "Leisure",
      item: "Entertainment",
      source: "",
      comment: "YouTube Premium",
    },
    {
      id: "HdeKn8laV4UToppK3jKq",
      isSpending: true,
      date: 1659819600000,
      sum: 90,
      icon: "🍗",
      tags: ["Myself", "Girlfriend", "Going out"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      sum: 0,
      date: 1659733200000,
    },
    {
      id: "taWWrJ8QQv2NPRb3bTsG",
      isSpending: true,
      date: 1659733200000,
      sum: 49,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Personal",
      source: "",
      comment: "Flowers",
    },
    {
      id: "rvs5eIb3xFJVo1C3hYHF",
      isSpending: true,
      date: 1659733200000,
      sum: 649,
      icon: "🛍️",
      tags: ["Myself"],
      group: "Purchases",
      item: "Gadgets",
      source: "",
      comment: "New smartphone",
    },
    {
      id: "qrrzxv231yrPELpoFIzF",
      isSpending: false,
      date: 1659733200000,
      sum: 10727,
      icon: "💰",
      tags: [],
      group: "",
      item: "",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1659560400000,
    },
    {
      id: "g2wZsaC699G9cYJZul59",
      isSpending: true,
      date: 1659560400000,
      sum: 10,
      icon: "🎁",
      tags: ["Myself"],
      group: "Gifts",
      item: "Donations",
      source: "",
      comment: "",
    },
    {
      id: "ZmRjtb6FHuE80laeEdIZ",
      isSpending: true,
      date: 1659560400000,
      sum: 128,
      icon: "🍗",
      tags: ["Myself", "Girlfriend", "Going out"],
      group: "Food",
      item: "Restaurant",
      source: "",
      comment: "",
    },
    {
      id: "Rr1UrwlwkKjqPeDaoECx",
      isSpending: false,
      date: 1659560400000,
      sum: 1200,
      icon: "🤷‍♂️",
      tags: [],
      group: "",
      item: "",
      source: "Odd Jobs",
      comment: "Built a website for Joe",
    },
    {
      sum: 0,
      date: 1659474000000,
    },
    {
      id: "YybcDu4b9ZMRns3iRfaY",
      isSpending: true,
      date: 1659474000000,
      sum: 38,
      icon: "🎁",
      tags: ["Myself"],
      group: "Gifts",
      item: "Donations",
      source: "Salary",
      comment: "",
    },
    {
      id: "LL5Jsc6z6jrVhnfsqGCq",
      isSpending: true,
      date: 1659474000000,
      sum: 57,
      icon: "🚕",
      tags: ["Myself"],
      group: "Transportation",
      item: "Gas",
      source: "",
      comment: "",
    },
    {
      id: "7QX3bUb2bZfysXTLrwX8",
      isSpending: true,
      date: 1659474000000,
      sum: 52,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Delivery",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1659387600000,
    },
    {
      id: "kGPeGH37u2XOY6zEtoCx",
      isSpending: true,
      date: 1659387600000,
      sum: 235,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "Salary",
      comment: "",
    },
    {
      id: "gucNm7eFMgxtFin1NHF7",
      isSpending: true,
      date: 1659387600000,
      sum: 157,
      icon: "🚕",
      tags: ["Myself"],
      group: "Transportation",
      item: "Gas",
      source: "Salary",
      comment: "",
    },
    {
      id: "DG8utyx06puFEYbubY79",
      isSpending: true,
      date: 1659387600000,
      sum: 10,
      icon: "🎁",
      tags: ["Myself"],
      group: "Gifts",
      item: "Donations",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1659301200000,
    },
    {
      id: "cw7NmtImYqCuUd4CCzin",
      isSpending: true,
      date: 1659301200000,
      sum: 36,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Fast Food",
      source: "",
      comment: "",
    },
    {
      id: "TW76TkdAFXrI6eAtPZYd",
      isSpending: true,
      date: 1659301200000,
      sum: 67,
      icon: "🍗",
      tags: ["Work-related"],
      group: "Food",
      item: "Delivery",
      source: "Salary",
      comment: "",
    },
    {
      id: "N5ucH5p4SLL24rRdcw1m",
      isSpending: true,
      date: 1659301200000,
      sum: 850,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Birthdays",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1659214800000,
    },
    {
      id: "hPUyxzI3uGfuBhbKiRcV",
      isSpending: true,
      date: 1659214800000,
      sum: 65,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Delivery",
      source: "Salary",
      comment: "",
    },
    {
      id: "5VyjvWI0yBBslnIfB8yY",
      isSpending: true,
      date: 1659214800000,
      sum: 30,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1659128400000,
    },
    {
      id: "vvtVP0nWDyOXoq0ADeW5",
      isSpending: true,
      date: 1659128400000,
      sum: 40,
      icon: "🕶️",
      tags: ["Myself", "Girlfriend"],
      group: "Leisure",
      item: "Culture",
      source: "Salary",
      comment: "Cinema",
    },
    {
      id: "aT3CyJlg1U7DLsaOLcaf",
      isSpending: true,
      date: 1659128400000,
      sum: 245,
      icon: "🍗",
      tags: ["Myself", "Girlfriend", "Family"],
      group: "Food",
      item: "Restaurant",
      source: "Salary",
      comment: "",
    },
    {
      id: "J1RucZnRCfaBTOsf0AIQ",
      isSpending: true,
      date: 1659128400000,
      sum: 99,
      icon: "🕶️",
      tags: ["Myself", "Girlfriend", "Family"],
      group: "Leisure",
      item: "Tours",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1659042000000,
    },
    {
      id: "iajgPnPFBJKlXmpdPEbt",
      isSpending: true,
      date: 1659042000000,
      sum: 55,
      icon: "👨‍⚕️",
      tags: ["Myself"],
      group: "Healthcare",
      item: "Pharmaceutical",
      source: "Salary",
      comment: "",
    },
    {
      id: "XiEDf81hMNvXg3qUf6FE",
      isSpending: false,
      date: 1659042000000,
      sum: 1483,
      icon: "🎩",
      tags: ["Myself"],
      group: "Food",
      item: "Restaurant",
      source: "Business",
      comment: "",
    },
    {
      id: "WPoTp10gn2yFW3ehTrE1",
      isSpending: true,
      date: 1659042000000,
      sum: 68,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Delivery",
      source: "Salary",
      comment: "",
    },
    {
      id: "TBns2bSZwPoFA7TtkMSn",
      isSpending: true,
      date: 1659042000000,
      sum: 100,
      icon: "👨‍⚕️",
      tags: ["Myself"],
      group: "Healthcare",
      item: "Appointments",
      source: "Salary",
      comment: "Cardiologist",
    },
    {
      sum: 0,
      date: 1658955600000,
    },
    {
      id: "7K2jwk9MrAUfzwLnpb7b",
      isSpending: true,
      date: 1658955600000,
      sum: 200,
      icon: "🔧",
      tags: ["Myself"],
      group: "Services",
      item: "Coaching",
      source: "Salary",
      comment: "Tennis",
    },
    {
      sum: 0,
      date: 1658869200000,
    },
    {
      id: "mwlP73x8wqrt7QZtKXvk",
      isSpending: false,
      date: 1658869200000,
      sum: 8766,
      icon: "💰",
      tags: ["Myself"],
      group: "Food",
      item: "Restaurant",
      source: "Salary",
      comment: "",
    },
    {
      id: "ed6sAWl7zUdIe49FAx0q",
      isSpending: true,
      date: 1658869200000,
      sum: 100,
      icon: "🚕",
      tags: ["Going out"],
      group: "Transportation",
      item: "Taxi",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1658782800000,
    },
    {
      id: "UKf4mu6pLQW8qkGw0bZg",
      isSpending: true,
      date: 1658782800000,
      sum: 68,
      icon: "🍗",
      tags: ["Work-related"],
      group: "Food",
      item: "Restaurant",
      source: "Salary",
      comment: "",
    },
    {
      id: "5JPgRLxptgvmhNUozYye",
      isSpending: true,
      date: 1658782800000,
      sum: 30,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Tobacco",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1658696400000,
    },
    {
      id: "sTvIXO18g9vwA3KSh8b2",
      isSpending: true,
      date: 1658696400000,
      sum: 97,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Personal",
      source: "Salary",
      comment: "",
    },
    {
      id: "XLgvnyFTBRIiSvkQhkUm",
      isSpending: true,
      date: 1658696400000,
      sum: 78,
      icon: "🍗",
      tags: ["Work-related"],
      group: "Food",
      item: "Restaurant",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1658610000000,
    },
    {
      id: "kjnp7OrWeA7Bx2zY511M",
      isSpending: true,
      date: 1658610000000,
      sum: 40,
      icon: "🚬",
      tags: ["Going out"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "Salary",
      comment: "",
    },
    {
      id: "cIlYPNpWL4FgCboyvZbd",
      isSpending: true,
      date: 1658610000000,
      sum: 53,
      icon: "🚕",
      tags: ["Myself"],
      group: "Transportation",
      item: "Gas",
      source: "Salary",
      comment: "",
    },
    {
      id: "Pz7McNxF3QeJc2pILdu8",
      isSpending: true,
      date: 1658610000000,
      sum: 136,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Restaurant",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1658523600000,
    },
    {
      id: "YzjxDLNSCJPLWKjhWiSo",
      isSpending: true,
      date: 1658523600000,
      sum: 300,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Home-Cooked",
      source: "Salary",
      comment: "",
    },
    {
      id: "FA07VndADKwIPK4yaI7u",
      isSpending: true,
      date: 1658523600000,
      sum: 66,
      icon: "🚕",
      tags: ["Myself"],
      group: "Transportation",
      item: "Taxi",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1658437200000,
    },
    {
      id: "SL22RqLv4S1AJuN6vSNY",
      isSpending: true,
      date: 1658437200000,
      sum: 48,
      icon: "🔧",
      tags: ["Myself"],
      group: "Services",
      item: "Haircut",
      source: "Salary",
      comment: "",
    },
    {
      id: "EJSN9JkFxJbpHN1Llx5J",
      isSpending: true,
      date: 1658437200000,
      sum: 70,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "Salary",
      comment: "",
    },
    {
      id: "0vaedYF90hC6g4Abia3P",
      isSpending: true,
      date: 1658437200000,
      sum: 99,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Restaurant",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1658350800000,
    },
    {
      id: "vOQjvBuAmVdPfxZmcnMl",
      isSpending: true,
      date: 1658350800000,
      sum: 47,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Snacks",
      source: "Salary",
      comment: "",
    },
    {
      id: "bcLxf3ZPSvzIbG9sTeZJ",
      isSpending: true,
      date: 1658350800000,
      sum: 30,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Tobacco",
      source: "Salary",
      comment: "",
    },
    {
      id: "I0xOw75CvImcqaIlkPFS",
      isSpending: true,
      date: 1658350800000,
      sum: 185,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Restaurant",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1658264400000,
    },
    {
      id: "M6tIMlIaTVaSdmAdhdCt",
      isSpending: true,
      date: 1658264400000,
      sum: 52,
      icon: "🚬",
      tags: ["Work-related"],
      group: "Bad Habits",
      item: "Fast Food",
      source: "Salary",
      comment: "",
    },
    {
      id: "FcP472yirPU9GEi54IZz",
      isSpending: true,
      date: 1658264400000,
      sum: 200,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Restaurant",
      source: "Salary",
      comment: "",
    },
    {
      id: "4dQ5vVoNq2excWIw4jPH",
      isSpending: true,
      date: 1658264400000,
      sum: 215,
      icon: "🔧",
      tags: ["Myself"],
      group: "Services",
      item: "Utilities",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1658178000000,
    },
    {
      id: "MUaY4fnOZYbkL7apBogI",
      isSpending: true,
      date: 1658178000000,
      sum: 23,
      icon: "🍗",
      tags: ["Work-related"],
      group: "Food",
      item: "Delivery",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1658091600000,
    },
    {
      id: "vBtOtRVlQ5OySTWyzAIV",
      isSpending: true,
      date: 1658091600000,
      sum: 10,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Snacks",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1658005200000,
    },
    {
      id: "Y0WTpb6lgn4NS9JkMfcy",
      isSpending: true,
      date: 1658005200000,
      sum: 40,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Snacks",
      source: "Salary",
      comment: "",
    },
    {
      id: "O0k7oQtftEL7FyrJXHMn",
      isSpending: true,
      date: 1658005200000,
      sum: 30,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Tobacco",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1657918800000,
    },
    {
      id: "s3UzV8CXtkCoTtBgMnQI",
      isSpending: true,
      date: 1657918800000,
      sum: 28,
      icon: "🚕",
      tags: ["Myself"],
      group: "Transportation",
      item: "Gas",
      source: "Salary",
      comment: "",
    },
    {
      id: "RZbyoclGThUEtyEgOch0",
      isSpending: true,
      date: 1657918800000,
      sum: 91,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Home-Cooked",
      source: "Salary",
      comment: "",
    },
    {
      id: "OpalSRiE7RCtLuVGVWCq",
      isSpending: true,
      date: 1657918800000,
      sum: 16,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "Salary",
      comment: "",
    },
    {
      id: "MishHLpq81IDAp9V8HYs",
      isSpending: true,
      date: 1657918800000,
      sum: 24,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1657832400000,
    },
    {
      id: "hTMYj8C3dNxVd3QMBS2B",
      isSpending: true,
      date: 1657832400000,
      sum: 53,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "Salary",
      comment: "",
    },
    {
      id: "58J9WexRYMWjp5u6K7gG",
      isSpending: true,
      date: 1657832400000,
      sum: 77,
      icon: "🍗",
      tags: ["Myself", "Girlfriend"],
      group: "Food",
      item: "Snacks",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1657659600000,
    },
    {
      id: "jdsA1RMxjp01PR4NdXD3",
      isSpending: true,
      date: 1657659600000,
      sum: 35,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Tobacco",
      source: "Salary",
      comment: "",
    },
    {
      id: "h08ypRgffvQ9ot0LFbSb",
      isSpending: true,
      date: 1657659600000,
      sum: 39,
      icon: "🍗",
      tags: ["Work-related"],
      group: "Food",
      item: "Delivery",
      source: "Salary",
      comment: "",
    },
    {
      id: "MnK8QBO2gBFd3yntGnWQ",
      isSpending: true,
      date: 1657659600000,
      sum: 5,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Snacks",
      source: "Salary",
      comment: "",
    },
    {
      id: "442IBvMrkHpA7uWgY1Mx",
      isSpending: true,
      date: 1657659600000,
      sum: 150,
      icon: "🎁",
      tags: ["Family"],
      group: "Gifts",
      item: "Birthdays",
      source: "Salary",
      comment: "Mom",
    },
    {
      sum: 0,
      date: 1657573200000,
    },
    {
      id: "syx3PjaLvVPSHOjcYZ1Y",
      isSpending: true,
      date: 1657573200000,
      sum: 26,
      icon: "🚕",
      tags: ["Going out"],
      group: "Transportation",
      item: "Taxi",
      source: "Salary",
      comment: "",
    },
    {
      id: "oHyYEw1IZn6Sq1STsnei",
      isSpending: true,
      date: 1657573200000,
      sum: 210,
      icon: "🚬",
      tags: ["Going out"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "Salary",
      comment: "",
    },
    {
      id: "jHpF6QDIdzLG7nibcMYB",
      isSpending: true,
      date: 1657573200000,
      sum: 36,
      icon: "🎁",
      tags: ["Going out"],
      group: "Gifts",
      item: "Personal",
      source: "Salary",
      comment: "Beer for Joe",
    },
    {
      sum: 0,
      date: 1657486800000,
    },
    {
      id: "yZVgWTYWxUsrJl2f4PI2",
      isSpending: true,
      date: 1657486800000,
      sum: 36,
      icon: "🍗",
      tags: ["Girlfriend"],
      group: "Food",
      item: "Snacks",
      source: "Salary",
      comment: "",
    },
    {
      id: "cOo2WtmwbPi20XBoJcQe",
      isSpending: true,
      date: 1657486800000,
      sum: 48,
      icon: "🍗",
      tags: ["Work-related"],
      group: "Food",
      item: "Delivery",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1657400400000,
    },
    {
      id: "imbTnjez07fknRCoJZrt",
      isSpending: true,
      date: 1657400400000,
      sum: 38,
      icon: "🚕",
      tags: ["Girlfriend"],
      group: "Transportation",
      item: "Taxi",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1657314000000,
    },
    {
      id: "gbUwelF0R7RJ3A3LcFSX",
      isSpending: true,
      date: 1657314000000,
      sum: 39,
      icon: "🎁",
      tags: ["Myself"],
      group: "Gifts",
      item: "Donations",
      source: "Salary",
      comment: "Wikipedia",
    },
    {
      id: "eY2NmmJj2npGjK7JkuEE",
      isSpending: true,
      date: 1657314000000,
      sum: 65,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Tobacco",
      source: "Salary",
      comment: "",
    },
    {
      id: "aQZWhuNUaTsERgfBsFmy",
      isSpending: true,
      date: 1657314000000,
      sum: 30,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Fast Food",
      source: "Salary",
      comment: "",
    },
    {
      id: "ZXRyids1nxjwEQ6QW5rE",
      isSpending: true,
      date: 1657314000000,
      sum: 58,
      icon: "🚬",
      tags: ["Going out"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "Salary",
      comment: "",
    },
    {
      id: "XVXE603x0maalHXeXOn0",
      isSpending: true,
      date: 1657314000000,
      sum: 68,
      icon: "🍗",
      tags: ["Going out"],
      group: "Food",
      item: "Snacks",
      source: "Salary",
      comment: "",
    },
    {
      id: "RjtFsjf0gBofcXQ6bW0Y",
      isSpending: true,
      date: 1657314000000,
      sum: 166,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1657227600000,
    },
    {
      id: "vlEWje5Ijfz2vbwh44tm",
      isSpending: true,
      date: 1657227600000,
      sum: 117,
      icon: "🚕",
      tags: ["Going out"],
      group: "Transportation",
      item: "Taxi",
      source: "Salary",
      comment: "",
    },
    {
      id: "ruNvmwFNJ3CJW05xdSTq",
      isSpending: true,
      date: 1657227600000,
      sum: 95,
      icon: "🍗",
      tags: ["Going out"],
      group: "Food",
      item: "Restaurant",
      source: "Salary",
      comment: "",
    },
    {
      id: "gToIUDQbRbYYSvEK36n3",
      isSpending: true,
      date: 1657227600000,
      sum: 48,
      icon: "🚕",
      tags: ["Going out"],
      group: "Transportation",
      item: "Taxi",
      source: "Salary",
      comment: "",
    },
    {
      id: "XpEsR84QsA5B9Y6lt2qt",
      isSpending: true,
      date: 1657227600000,
      sum: 26,
      icon: "🚬",
      tags: ["Going out"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "Salary",
      comment: "",
    },
    {
      id: "UHIRdQv2GtT0hA3hjJfC",
      isSpending: true,
      date: 1657227600000,
      sum: 16,
      icon: "🎁",
      tags: ["Going out"],
      group: "Gifts",
      item: "Personal",
      source: "Salary",
      comment: "Beer for Joe",
    },
    {
      id: "MX8CWGpyggqYLxyXnv1E",
      isSpending: true,
      date: 1657227600000,
      sum: 59,
      icon: "🍗",
      tags: ["Going out"],
      group: "Food",
      item: "Snacks",
      source: "Salary",
      comment: "",
    },
    {
      id: "KTcZF7MSmB8YhXU647dg",
      isSpending: true,
      date: 1657227600000,
      sum: 43,
      icon: "🚬",
      tags: ["Myself", "Girlfriend", "Going out"],
      group: "Bad Habits",
      item: "Fast Food",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1657141200000,
    },
    {
      id: "XhmC3fFnEaJs6oeSad10",
      isSpending: true,
      date: 1657141200000,
      sum: 12,
      icon: "🕶️",
      tags: ["Myself"],
      group: "Leisure",
      item: "Entertainment",
      source: "Salary",
      comment: "YouTube Premium",
    },
    {
      id: "R88LmJhMdiiU7z4UQ3Fj",
      isSpending: true,
      date: 1657141200000,
      sum: 60,
      icon: "🚬",
      tags: ["Myself"],
      group: "Bad Habits",
      item: "Tobacco",
      source: "Salary",
      comment: "",
    },
    {
      id: "R4D2B1FU1T45ohr4IYNN",
      isSpending: true,
      date: 1657141200000,
      sum: 24,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "Salary",
      comment: "",
    },
    {
      id: "EuwAkaxl1PQlKFQXmGLI",
      isSpending: false,
      date: 1657141200000,
      sum: 6567,
      icon: "💰",
      tags: ["Myself"],
      group: "Food",
      item: "Restaurant",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1657054800000,
    },
    {
      id: "zFYfZ3qzZWsTxbkWoc8b",
      isSpending: true,
      date: 1657054800000,
      sum: 78,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Personal",
      source: "Salary",
      comment: "",
    },
    {
      id: "RathaKXbmziFIjDYPsLu",
      isSpending: true,
      date: 1657054800000,
      sum: 30,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Snacks",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1656968400000,
    },
    {
      id: "eJ5UzU8Sv2lEmvCysBMR",
      isSpending: true,
      date: 1656968400000,
      sum: 233,
      icon: "🔝",
      tags: ["Business"],
      group: "Investments",
      item: "Paid Ads",
      source: "Salary",
      comment: "Facebook Ads",
    },
    {
      sum: 0,
      date: 1656795600000,
    },
    {
      id: "YkY1E5VUFDAbrYPBDBcb",
      isSpending: true,
      date: 1656795600000,
      sum: 63,
      icon: "🚬",
      tags: ["Going out"],
      group: "Bad Habits",
      item: "Tobacco",
      source: "Salary",
      comment: "",
    },
    {
      id: "QdxUMqjMC4gTUXNINi4j",
      isSpending: true,
      date: 1656795600000,
      sum: 89,
      icon: "🚬",
      tags: ["Going out"],
      group: "Bad Habits",
      item: "Alcohol",
      source: "Salary",
      comment: "",
    },
    {
      id: "Il1i1HgCNbGGMKvvAKbF",
      isSpending: false,
      date: 1656795600000,
      sum: 8000,
      icon: "🎩",
      tags: ["Myself"],
      group: "Food",
      item: "Restaurant",
      source: "Business",
      comment: "",
    },
    {
      id: "FjDDAFlaMmxRvYvqd5Ut",
      isSpending: true,
      date: 1656795600000,
      sum: 26,
      icon: "🎁",
      tags: ["Girlfriend"],
      group: "Gifts",
      item: "Personal",
      source: "Salary",
      comment: "",
    },
    {
      id: "2ulgDNbp3m8HtYUsuFpE",
      isSpending: true,
      date: 1656795600000,
      sum: 33,
      icon: "🍗",
      tags: ["Travels", "Myself"],
      group: "Food",
      item: "Snacks",
      source: "Salary",
      comment: "",
    },
    {
      id: "2u85kIs8mN3UP8sTwyAs",
      isSpending: true,
      date: 1656795600000,
      sum: 111,
      icon: "🍗",
      tags: ["Myself"],
      group: "Food",
      item: "Home-Cooked",
      source: "Salary",
      comment: "",
    },
    {
      sum: 0,
      date: 1656709200000,
    },
    {
      id: "ohKBktINsP7S5pbfSnVr",
      isSpending: false,
      date: 1656709200000,
      sum: 1041,
      icon: "💰",
      tags: ["Myself"],
      group: "Food",
      item: "Restaurant",
      source: "Salary",
      comment: "",
    },
  ],
};
